[supervisord]
nodaemon=true
user=root
logfile=/app/data/logs/supervisord.log
loglevel=error
pidfile=/app/data/tmp/supervisord.pid
logfile_maxbytes=10MB
logfile_backups=5

[program:sshd]
command=/usr/sbin/sshd -D -e -f /etc/ssh/sshd_config
stdout_logfile=/app/data/tmp/sshd.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
redirect_stderr=true

[program:borgwarehouse]
command=/usr/local/bin/node server.js
user=node
environment=HOME="/home/node",NODE_ENV="%(ENV_NODE_ENV)s",CONFIG_PATH="%(ENV_CONFIG_PATH)s",NEXTAUTH_SECRET="%(ENV_NEXTAUTH_SECRET)s",NEXTAUTH_URL="%(ENV_NEXTAUTH_URL)s",CRONJOB_KEY="%(ENV_CRONJOB_KEY)s",FQDN="%(ENV_FQDN)s",SSH_SERVER_PORT="%(ENV_SSH_SERVER_PORT)s",SSH_SERVER_FINGERPRINT_RSA="%(ENV_SSH_SERVER_FINGERPRINT_RSA)s",SSH_SERVER_FINGERPRINT_ED25519="%(ENV_SSH_SERVER_FINGERPRINT_ED25519)s",SSH_SERVER_FINGERPRINT_ECDSA="%(ENV_SSH_SERVER_FINGERPRINT_ECDSA)s"
stdout_logfile=/app/data/tmp/borgwarehouse.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
redirect_stderr=true

[program:rsyslogd]
command=rsyslogd -n -i /app/data/tmp/rsyslogd.pid -f /etc/rsyslog.conf