[supervisord]
nodaemon=true
logfile=/app/data/logs/supervisord.log
loglevel=error
pidfile=/app/data/tmp/supervisord.pid
logfile_maxbytes=10MB
logfile_backups=5

[program:sshd]
command=/usr/sbin/sshd -D -e -f /etc/ssh/sshd_config
stdout_logfile=/app/data/tmp/sshd.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
redirect_stderr=true

[program:borgwarehouse]
command=/usr/local/bin/node server.js
user=node
environment=HOME="/home/node"
stdout_logfile=/app/data/tmp/borgwarehouse.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
redirect_stderr=true

[program:rsyslogd]
command=rsyslogd -n -i /app/data/tmp/rsyslogd.pid -f /etc/rsyslog.conf